#!/bin/bash
#
# chkconfig: 2345 98 8
# description: SinusBot Otomatik Baslatici | HGMNetwork
#
######################################################################
## HGMNetwork SinusBot Otomatik Baslatici Script V5.22 Guncellemesi ##
######################################################################
## Coder/Developer: HGMNetwork By HGM                               ##
######################################################################
##                                                                  ##
## Merhaba..! Eger Burayi Okuyorsan Buyuk Ihtimalle Bu Dosyayi.     ##
## Bulmus Ve Merak Etmis Olmalisin.                                 ##
## Bu Gayet Normal, HGMNetwork.v5 Scripti Kendisi Disindaki,        ##
## Ozellikleri Genellikle Acik-Kaynak Olarak Birakir, Saklamaz.     ##
## Bunun Nedeni Bizim Trojan/Virus Icerikli Oldugunu Iddia Eden     ##
## Bazi Akil Yoksullari Arasindan Azicik Yazilim/Kodlamadan         ##
## Anlayan Insanlarin Bu Kodlari Inceleyip Gercekleri Gorsunler     ##
## Istedik, Kodlar Assagidaki Gibidir Istedigin Sekillerde          ##
## Inceleyebilir Ve Modifiye Edebilirsin, En Ufak Bir Sorun Olmaz   ##
## Modifiyeden Kastim Kesinlikle Script Adini Degisip Sonrada       ##
## "bEn kOdLaDiM/BeN yAptIm" Diyerek Paylasmak Degildir. Dipnot:    ##
## Benden Caldiklarinizla SAKIN OLA SANAL ALEMDE SAHSIM Icin        ##
## Hirsizlikla Suclamada Bulunmayin Aksi Taktirde Rezil Olursunuz.  ##
##                                                                  ##
######################################################################
##                                                                  ##
######################################################################
##                                ##
####################################
## Burayi Kesinlikle Ellemeyin..! ##
####################################
##                                ##
HGMNetwork_OtoSinusBaslat_SuDizini=(/bin/su)
HGMNetwork_OtoSinusBaslat_Kullanici=(sinusbot)
######################################################################

case $1 in

start)
$HGMNetwork_OtoSinusBaslat_SuDizini $HGMNetwork_OtoSinusBaslat_Kullanici -c "cd /opt/ts3soundboard$HGMNetwork_OtoSinusBaslat_BotPort/; screen -A -m -d -S 'sinusbot$HGMNetwork_OtoSinusBaslat_BotPort' ./sinusbot"
 ;;
stop)
$HGMNetwork_OtoSinusBaslat_SuDizini $HGMNetwork_OtoSinusBaslat_Kullanici -c "screen -X -S 'sinusbot$HGMNetwork_OtoSinusBaslat_BotPort' quit"
 ;;
restart)
$HGMNetwork_OtoSinusBaslat_SuDizini $HGMNetwork_OtoSinusBaslat_Kullanici -c "screen -X -S 'sinusbot$HGMNetwork_OtoSinusBaslat_BotPort' quit"
$HGMNetwork_OtoSinusBaslat_SuDizini $HGMNetwork_OtoSinusBaslat_Kullanici -c "cd /opt/ts3soundboard$HGMNetwork_OtoSinusBaslat_BotPort/; screen -A -m -d -S 'sinusbot$HGMNetwork_OtoSinusBaslat_BotPort' ./sinusbot"
 ;;
*)
echo -e "HGMNetwork-Oto-SinusBot-Baslatici Kullanim: {start|stop|restart}"
exit 0
 ;;

esac
